name: transparency_camera_overlay_for_transitions
description: "A video recording application that overlays the paused frame so that the user can align the next frame carefully."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  path: ^1.9.0
  camera: ^0.11.2 #main camera dependency
  gal: ^2.3.2 #for storing to gallery
  permission_handler: ^11.0.1 #permission maangane vaaste

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
